### ISSUE TITLE
小規模保育園「キッズランド未来」の緯度経度が正しくない

### ISSUE THREAD

**Issue by aca-ta** [Code-for-Funabashi/open-data-parser#10]
open-data-parserで出力された緯度経度: 35.7554234, 140.0232974

本来の緯度経度: 35.755853,140.0221113

[googlemap](https://www.google.co.jp/maps/place/%E3%82%AD%E3%83%83%E3%82%BA%E3%83%A9%E3%83%B3%E3%83%89%E6%9C%AA%E6%9D%A5/@35.755853,140.0221113,17z/data=!3m1!4b1!4m5!3m4!1s0x60227f794a26c3c5:0xcd65606bd8413500!8m2!3d35.755855!4d140.0242916)

**Comment by Jumpo-523** [comment]
サポート問い合わせしました。回答お待ちください！

**Comment by Jumpo-523** [comment]
[pull #11](https://github.com/Code-for-Funabashi/open-data-parser/pull/11)の動作確認で判明したズレ記載

```diff
   {
     "name": "キッズランド未来",
-    "lat": 35.7554234,
-    "lng": 140.0232974,
+    "lat": 35.7549382,
+    "lng": 140.0223346,
     "details": {
       "address": "船橋市二和東6-18-27　1階",
       "phone_number": "047-448-7735"
@@ -217,8 +217,8 @@
   },
   {
     "name": "ひだまり保育園",
-    "lat": 35.7102321,
-    "lng": 140.0376168,
+    "lat": 35.7102596,
+    "lng": 140.0378286,
     "details": {
       "address": "船橋市薬円台6-1-1",
       "phone_number": "047-404-8511"
```

**Comment by aca-ta** [comment]
#14 直した
クローズ
